# Generated by Django 4.1.3 on 2022-12-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=250, verbose_name='دامنه سایت')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
                ('site_phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='تلفن')),
                ('site_fax', models.CharField(blank=True, max_length=250, null=True, verbose_name='فکس')),
                ('site_email', models.CharField(blank=True, max_length=250, null=True, verbose_name='ایمیل')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت سایت')),
                ('about_us', models.TextField(verbose_name='متن درباره ما')),
                ('site_logo', models.ImageField(max_length=250, upload_to='images/site_settings/site_logo', verbose_name='لوگو سایت')),
                ('is_main_settings', models.BooleanField(max_length=250, verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
