# Generated by Django 4.1.3 on 2022-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات اسلایدر')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.URLField(max_length=650, verbose_name='آدرس لینک')),
                ('image', models.ImageField(upload_to='images/slider_images')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
