# Generated by Django 4.1.3 on 2022-12-09 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2022, 12, 9), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
