# Generated by Django 4.1.3 on 2022-12-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_articlecomment_admin_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='admin_confirm',
        ),
    ]
